version: "3"
services:
  nginx:
    image: nginx
    container_name: Neo_nginx2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
