// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/Admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Admin) Reset() {
	*x = Admin{}
	mi := &file_proto_Admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{0}
}

func (x *Admin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Admin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Admin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAndValidateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAndValidateAdminRequest) Reset() {
	*x = GetAndValidateAdminRequest{}
	mi := &file_proto_Admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAndValidateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAndValidateAdminRequest) ProtoMessage() {}

func (x *GetAndValidateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAndValidateAdminRequest.ProtoReflect.Descriptor instead.
func (*GetAndValidateAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetAndValidateAdminRequest) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

type AllAdmins struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllAdmins) Reset() {
	*x = AllAdmins{}
	mi := &file_proto_Admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllAdmins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllAdmins) ProtoMessage() {}

func (x *AllAdmins) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllAdmins.ProtoReflect.Descriptor instead.
func (*AllAdmins) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{2}
}

var File_proto_Admin_proto protoreflect.FileDescriptor

const file_proto_Admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/Admin.proto\x12\x05admin\"A\n" +
	"\x05Admin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"0\n" +
	"\x1aGetAndValidateAdminRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\"\v\n" +
	"\tAllAdmins2}\n" +
	"\fAdminService\x12=\n" +
	"\bGetAdmin\x12!.admin.GetAndValidateAdminRequest\x1a\f.admin.Admin\"\x00\x12.\n" +
	"\bAllAdmin\x12\x10.admin.AllAdmins\x1a\f.admin.Admin\"\x000\x01B)Z'github.com/kiddo9/SMS-MAIL-SERVER/protob\x06proto3"

var (
	file_proto_Admin_proto_rawDescOnce sync.Once
	file_proto_Admin_proto_rawDescData []byte
)

func file_proto_Admin_proto_rawDescGZIP() []byte {
	file_proto_Admin_proto_rawDescOnce.Do(func() {
		file_proto_Admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Admin_proto_rawDesc), len(file_proto_Admin_proto_rawDesc)))
	})
	return file_proto_Admin_proto_rawDescData
}

var file_proto_Admin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_Admin_proto_goTypes = []any{
	(*Admin)(nil),                      // 0: admin.Admin
	(*GetAndValidateAdminRequest)(nil), // 1: admin.GetAndValidateAdminRequest
	(*AllAdmins)(nil),                  // 2: admin.AllAdmins
}
var file_proto_Admin_proto_depIdxs = []int32{
	1, // 0: admin.AdminService.GetAdmin:input_type -> admin.GetAndValidateAdminRequest
	2, // 1: admin.AdminService.AllAdmin:input_type -> admin.AllAdmins
	0, // 2: admin.AdminService.GetAdmin:output_type -> admin.Admin
	0, // 3: admin.AdminService.AllAdmin:output_type -> admin.Admin
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Admin_proto_init() }
func file_proto_Admin_proto_init() {
	if File_proto_Admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Admin_proto_rawDesc), len(file_proto_Admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Admin_proto_goTypes,
		DependencyIndexes: file_proto_Admin_proto_depIdxs,
		MessageInfos:      file_proto_Admin_proto_msgTypes,
	}.Build()
	File_proto_Admin_proto = out.File
	file_proto_Admin_proto_goTypes = nil
	file_proto_Admin_proto_depIdxs = nil
}
