// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/Admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Otp           int64                  `protobuf:"varint,5,opt,name=otp,proto3" json:"otp,omitempty"`
	OtpExpiry     float64                `protobuf:"fixed64,6,opt,name=otpExpiry,proto3" json:"otpExpiry,omitempty"` // Unix timestamp in seconds
	APIKey        string                 `protobuf:"bytes,7,opt,name=APIKey,proto3" json:"APIKey,omitempty"`
	Uuid          string                 `protobuf:"bytes,8,opt,name=uuid,proto3" json:"uuid,omitempty"`                     // Unique identifier for the admin
	Jwt           string                 `protobuf:"bytes,9,opt,name=jwt,proto3" json:"jwt,omitempty"`                       // JWT token for authentication
	EmailVerified bool                   `protobuf:"varint,10,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"` // Indicates if the email is verified
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`          // Timestamp of when the admin was created
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`          // Timestamp of when the admin was last updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Admin) Reset() {
	*x = Admin{}
	mi := &file_proto_Admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{0}
}

func (x *Admin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Admin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Admin) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Admin) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Admin) GetOtp() int64 {
	if x != nil {
		return x.Otp
	}
	return 0
}

func (x *Admin) GetOtpExpiry() float64 {
	if x != nil {
		return x.OtpExpiry
	}
	return 0
}

func (x *Admin) GetAPIKey() string {
	if x != nil {
		return x.APIKey
	}
	return ""
}

func (x *Admin) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Admin) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *Admin) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *Admin) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Admin) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateAdminUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecaptchaToken string                 `protobuf:"bytes,1,opt,name=recaptchaToken,proto3" json:"recaptchaToken,omitempty"` // Recaptcha token for validation
	Admin          *Admin                 `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`                   // Admin details to be created
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAdminUserRequest) Reset() {
	*x = CreateAdminUserRequest{}
	mi := &file_proto_Admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminUserRequest) ProtoMessage() {}

func (x *CreateAdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminUserRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdminUserRequest) GetRecaptchaToken() string {
	if x != nil {
		return x.RecaptchaToken
	}
	return ""
}

func (x *CreateAdminUserRequest) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type CreateAdminUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminCreated  bool                   `protobuf:"varint,1,opt,name=adminCreated,proto3" json:"adminCreated,omitempty"` // Created admin details
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`            // Message regarding the creation status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminUserResponse) Reset() {
	*x = CreateAdminUserResponse{}
	mi := &file_proto_Admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminUserResponse) ProtoMessage() {}

func (x *CreateAdminUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminUserResponse.ProtoReflect.Descriptor instead.
func (*CreateAdminUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdminUserResponse) GetAdminCreated() bool {
	if x != nil {
		return x.AdminCreated
	}
	return false
}

func (x *CreateAdminUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAndValidateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // Email of the admin to be validated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAndValidateAdminRequest) Reset() {
	*x = GetAndValidateAdminRequest{}
	mi := &file_proto_Admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAndValidateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAndValidateAdminRequest) ProtoMessage() {}

func (x *GetAndValidateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAndValidateAdminRequest.ProtoReflect.Descriptor instead.
func (*GetAndValidateAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetAndValidateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ValidateAdminResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsValid         bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`                 // Indicates if the admin is valid
	Admin           *Admin                 `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`                      // Admin details if valid
	IsEmailVerified bool                   `protobuf:"varint,3,opt,name=isEmailVerified,proto3" json:"isEmailVerified,omitempty"` // Indicates if the email is verified
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                  // Message regarding the validation status
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateAdminResponse) Reset() {
	*x = ValidateAdminResponse{}
	mi := &file_proto_Admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAdminResponse) ProtoMessage() {}

func (x *ValidateAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAdminResponse.ProtoReflect.Descriptor instead.
func (*ValidateAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateAdminResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateAdminResponse) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *ValidateAdminResponse) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *ValidateAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AllAdmins struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllAdmins) Reset() {
	*x = AllAdmins{}
	mi := &file_proto_Admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllAdmins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllAdmins) ProtoMessage() {}

func (x *AllAdmins) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllAdmins.ProtoReflect.Descriptor instead.
func (*AllAdmins) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{5}
}

type OtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // Email of the admin to send OTP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpRequest) Reset() {
	*x = OtpRequest{}
	mi := &file_proto_Admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpRequest) ProtoMessage() {}

func (x *OtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpRequest.ProtoReflect.Descriptor instead.
func (*OtpRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{6}
}

func (x *OtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpSent       bool                   `protobuf:"varint,1,opt,name=otpSent,proto3" json:"otpSent,omitempty"` // Indicates if the OTP was sent successfully
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Message regarding the OTP status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpResponse) Reset() {
	*x = OtpResponse{}
	mi := &file_proto_Admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpResponse) ProtoMessage() {}

func (x *OtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpResponse.ProtoReflect.Descriptor instead.
func (*OtpResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{7}
}

func (x *OtpResponse) GetOtpSent() bool {
	if x != nil {
		return x.OtpSent
	}
	return false
}

func (x *OtpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OtpVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // Email of the admin for OTP verification
	Otp           int64                  `protobuf:"varint,2,opt,name=otp,proto3" json:"otp,omitempty"`    // OTP to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpVerificationRequest) Reset() {
	*x = OtpVerificationRequest{}
	mi := &file_proto_Admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpVerificationRequest) ProtoMessage() {}

func (x *OtpVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpVerificationRequest.ProtoReflect.Descriptor instead.
func (*OtpVerificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{8}
}

func (x *OtpVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OtpVerificationRequest) GetOtp() int64 {
	if x != nil {
		return x.Otp
	}
	return 0
}

type OtpVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsVerified    bool                   `protobuf:"varint,1,opt,name=isVerified,proto3" json:"isVerified,omitempty"` // Indicates if the OTP verification was successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`        // Message regarding the verification status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpVerificationResponse) Reset() {
	*x = OtpVerificationResponse{}
	mi := &file_proto_Admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpVerificationResponse) ProtoMessage() {}

func (x *OtpVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpVerificationResponse.ProtoReflect.Descriptor instead.
func (*OtpVerificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{9}
}

func (x *OtpVerificationResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *OtpVerificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetASpecificAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Unique identifier of the admin to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetASpecificAdminRequest) Reset() {
	*x = GetASpecificAdminRequest{}
	mi := &file_proto_Admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetASpecificAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetASpecificAdminRequest) ProtoMessage() {}

func (x *GetASpecificAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetASpecificAdminRequest.ProtoReflect.Descriptor instead.
func (*GetASpecificAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetASpecificAdminRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetASpecificAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"` // Admin details if found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetASpecificAdminResponse) Reset() {
	*x = GetASpecificAdminResponse{}
	mi := &file_proto_Admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetASpecificAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetASpecificAdminResponse) ProtoMessage() {}

func (x *GetASpecificAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetASpecificAdminResponse.ProtoReflect.Descriptor instead.
func (*GetASpecificAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetASpecificAdminResponse) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"` // Admin details to be updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateRequest) Reset() {
	*x = AdminUpdateRequest{}
	mi := &file_proto_Admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateRequest) ProtoMessage() {}

func (x *AdminUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminUpdateRequest) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUpdated     bool                   `protobuf:"varint,1,opt,name=isUpdated,proto3" json:"isUpdated,omitempty"` // Indicates if the admin was updated successfully
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // Message regarding the update status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateResponse) Reset() {
	*x = AdminUpdateResponse{}
	mi := &file_proto_Admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateResponse) ProtoMessage() {}

func (x *AdminUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminUpdateResponse) GetIsUpdated() bool {
	if x != nil {
		return x.IsUpdated
	}
	return false
}

func (x *AdminUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Unique identifier of the admin to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_proto_Admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteAdminRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDeleted     bool                   `protobuf:"varint,1,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"` // Indicates if the admin was deleted successfully
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // Message regarding the deletion status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminResponse) Reset() {
	*x = DeleteAdminResponse{}
	mi := &file_proto_Admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminResponse) ProtoMessage() {}

func (x *DeleteAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteAdminResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *DeleteAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TokenValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT token to validate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidationRequest) Reset() {
	*x = TokenValidationRequest{}
	mi := &file_proto_Admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationRequest) ProtoMessage() {}

func (x *TokenValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationRequest.ProtoReflect.Descriptor instead.
func (*TokenValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{16}
}

func (x *TokenValidationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"` // Indicates if the token is valid
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`      // Message regarding the token validation status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidationResponse) Reset() {
	*x = TokenValidationResponse{}
	mi := &file_proto_Admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationResponse) ProtoMessage() {}

func (x *TokenValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationResponse.ProtoReflect.Descriptor instead.
func (*TokenValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_Admin_proto_rawDescGZIP(), []int{17}
}

func (x *TokenValidationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *TokenValidationResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_Admin_proto protoreflect.FileDescriptor

const file_proto_Admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/Admin.proto\x12\x05admin\"\xab\x02\n" +
	"\x05Admin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x10\n" +
	"\x03otp\x18\x05 \x01(\x03R\x03otp\x12\x1c\n" +
	"\totpExpiry\x18\x06 \x01(\x01R\totpExpiry\x12\x16\n" +
	"\x06APIKey\x18\a \x01(\tR\x06APIKey\x12\x12\n" +
	"\x04uuid\x18\b \x01(\tR\x04uuid\x12\x10\n" +
	"\x03jwt\x18\t \x01(\tR\x03jwt\x12$\n" +
	"\remailVerified\x18\n" +
	" \x01(\bR\remailVerified\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\tR\tupdatedAt\"d\n" +
	"\x16CreateAdminUserRequest\x12&\n" +
	"\x0erecaptchaToken\x18\x01 \x01(\tR\x0erecaptchaToken\x12\"\n" +
	"\x05admin\x18\x02 \x01(\v2\f.admin.AdminR\x05admin\"W\n" +
	"\x17CreateAdminUserResponse\x12\"\n" +
	"\fadminCreated\x18\x01 \x01(\bR\fadminCreated\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x1aGetAndValidateAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x99\x01\n" +
	"\x15ValidateAdminResponse\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\x12\"\n" +
	"\x05admin\x18\x02 \x01(\v2\f.admin.AdminR\x05admin\x12(\n" +
	"\x0fisEmailVerified\x18\x03 \x01(\bR\x0fisEmailVerified\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\v\n" +
	"\tAllAdmins\"\"\n" +
	"\n" +
	"OtpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"A\n" +
	"\vOtpResponse\x12\x18\n" +
	"\aotpSent\x18\x01 \x01(\bR\aotpSent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x16OtpVerificationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\x03R\x03otp\"S\n" +
	"\x17OtpVerificationResponse\x12\x1e\n" +
	"\n" +
	"isVerified\x18\x01 \x01(\bR\n" +
	"isVerified\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x18GetASpecificAdminRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"?\n" +
	"\x19GetASpecificAdminResponse\x12\"\n" +
	"\x05admin\x18\x01 \x01(\v2\f.admin.AdminR\x05admin\"8\n" +
	"\x12AdminUpdateRequest\x12\"\n" +
	"\x05admin\x18\x01 \x01(\v2\f.admin.AdminR\x05admin\"M\n" +
	"\x13AdminUpdateResponse\x12\x1c\n" +
	"\tisUpdated\x18\x01 \x01(\bR\tisUpdated\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\x12DeleteAdminRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"M\n" +
	"\x13DeleteAdminResponse\x12\x1c\n" +
	"\tisDeleted\x18\x01 \x01(\bR\tisDeleted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x16TokenValidationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x17TokenValidationResponse\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\xda\x05\n" +
	"\fAdminService\x12N\n" +
	"\vCreateAdmin\x12\x1d.admin.CreateAdminUserRequest\x1a\x1e.admin.CreateAdminUserResponse\"\x00\x122\n" +
	"\fGetAllAdmins\x12\x10.admin.AllAdmins\x1a\f.admin.Admin\"\x000\x01\x12R\n" +
	"\rValidateAdmin\x12!.admin.GetAndValidateAdminRequest\x1a\x1c.admin.ValidateAdminResponse\"\x00\x122\n" +
	"\aSendOtp\x12\x11.admin.OtpRequest\x1a\x12.admin.OtpResponse\"\x00\x12L\n" +
	"\tVerifyOtp\x12\x1d.admin.OtpVerificationRequest\x1a\x1e.admin.OtpVerificationResponse\"\x00\x125\n" +
	"\n" +
	"LoginAdmin\x12\x11.admin.OtpRequest\x1a\x12.admin.OtpResponse\"\x00\x12W\n" +
	"\x10GetSpecificAdmin\x12\x1f.admin.GetASpecificAdminRequest\x1a .admin.GetASpecificAdminResponse\"\x00\x12F\n" +
	"\vUpdateAdmin\x12\x19.admin.AdminUpdateRequest\x1a\x1a.admin.AdminUpdateResponse\"\x00\x12F\n" +
	"\vDeleteAdmin\x12\x19.admin.DeleteAdminRequest\x1a\x1a.admin.DeleteAdminResponse\"\x00\x12P\n" +
	"\rValidateToken\x12\x1d.admin.TokenValidationRequest\x1a\x1e.admin.TokenValidationResponse\"\x00B\x0fZ\rmessage/protob\x06proto3"

var (
	file_proto_Admin_proto_rawDescOnce sync.Once
	file_proto_Admin_proto_rawDescData []byte
)

func file_proto_Admin_proto_rawDescGZIP() []byte {
	file_proto_Admin_proto_rawDescOnce.Do(func() {
		file_proto_Admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Admin_proto_rawDesc), len(file_proto_Admin_proto_rawDesc)))
	})
	return file_proto_Admin_proto_rawDescData
}

var file_proto_Admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_Admin_proto_goTypes = []any{
	(*Admin)(nil),                      // 0: admin.Admin
	(*CreateAdminUserRequest)(nil),     // 1: admin.CreateAdminUserRequest
	(*CreateAdminUserResponse)(nil),    // 2: admin.CreateAdminUserResponse
	(*GetAndValidateAdminRequest)(nil), // 3: admin.GetAndValidateAdminRequest
	(*ValidateAdminResponse)(nil),      // 4: admin.ValidateAdminResponse
	(*AllAdmins)(nil),                  // 5: admin.AllAdmins
	(*OtpRequest)(nil),                 // 6: admin.OtpRequest
	(*OtpResponse)(nil),                // 7: admin.OtpResponse
	(*OtpVerificationRequest)(nil),     // 8: admin.OtpVerificationRequest
	(*OtpVerificationResponse)(nil),    // 9: admin.OtpVerificationResponse
	(*GetASpecificAdminRequest)(nil),   // 10: admin.GetASpecificAdminRequest
	(*GetASpecificAdminResponse)(nil),  // 11: admin.GetASpecificAdminResponse
	(*AdminUpdateRequest)(nil),         // 12: admin.AdminUpdateRequest
	(*AdminUpdateResponse)(nil),        // 13: admin.AdminUpdateResponse
	(*DeleteAdminRequest)(nil),         // 14: admin.DeleteAdminRequest
	(*DeleteAdminResponse)(nil),        // 15: admin.DeleteAdminResponse
	(*TokenValidationRequest)(nil),     // 16: admin.TokenValidationRequest
	(*TokenValidationResponse)(nil),    // 17: admin.TokenValidationResponse
}
var file_proto_Admin_proto_depIdxs = []int32{
	0,  // 0: admin.CreateAdminUserRequest.admin:type_name -> admin.Admin
	0,  // 1: admin.ValidateAdminResponse.admin:type_name -> admin.Admin
	0,  // 2: admin.GetASpecificAdminResponse.admin:type_name -> admin.Admin
	0,  // 3: admin.AdminUpdateRequest.admin:type_name -> admin.Admin
	1,  // 4: admin.AdminService.CreateAdmin:input_type -> admin.CreateAdminUserRequest
	5,  // 5: admin.AdminService.GetAllAdmins:input_type -> admin.AllAdmins
	3,  // 6: admin.AdminService.ValidateAdmin:input_type -> admin.GetAndValidateAdminRequest
	6,  // 7: admin.AdminService.SendOtp:input_type -> admin.OtpRequest
	8,  // 8: admin.AdminService.VerifyOtp:input_type -> admin.OtpVerificationRequest
	6,  // 9: admin.AdminService.LoginAdmin:input_type -> admin.OtpRequest
	10, // 10: admin.AdminService.GetSpecificAdmin:input_type -> admin.GetASpecificAdminRequest
	12, // 11: admin.AdminService.UpdateAdmin:input_type -> admin.AdminUpdateRequest
	14, // 12: admin.AdminService.DeleteAdmin:input_type -> admin.DeleteAdminRequest
	16, // 13: admin.AdminService.ValidateToken:input_type -> admin.TokenValidationRequest
	2,  // 14: admin.AdminService.CreateAdmin:output_type -> admin.CreateAdminUserResponse
	0,  // 15: admin.AdminService.GetAllAdmins:output_type -> admin.Admin
	4,  // 16: admin.AdminService.ValidateAdmin:output_type -> admin.ValidateAdminResponse
	7,  // 17: admin.AdminService.SendOtp:output_type -> admin.OtpResponse
	9,  // 18: admin.AdminService.VerifyOtp:output_type -> admin.OtpVerificationResponse
	7,  // 19: admin.AdminService.LoginAdmin:output_type -> admin.OtpResponse
	11, // 20: admin.AdminService.GetSpecificAdmin:output_type -> admin.GetASpecificAdminResponse
	13, // 21: admin.AdminService.UpdateAdmin:output_type -> admin.AdminUpdateResponse
	15, // 22: admin.AdminService.DeleteAdmin:output_type -> admin.DeleteAdminResponse
	17, // 23: admin.AdminService.ValidateToken:output_type -> admin.TokenValidationResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_Admin_proto_init() }
func file_proto_Admin_proto_init() {
	if File_proto_Admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Admin_proto_rawDesc), len(file_proto_Admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Admin_proto_goTypes,
		DependencyIndexes: file_proto_Admin_proto_depIdxs,
		MessageInfos:      file_proto_Admin_proto_msgTypes,
	}.Build()
	File_proto_Admin_proto = out.File
	file_proto_Admin_proto_goTypes = nil
	file_proto_Admin_proto_depIdxs = nil
}
