// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/FileUpload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_proto_FileUpload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_FileUpload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_FileUpload_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	mi := &file_proto_FileUpload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_FileUpload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_FileUpload_proto_rawDescGZIP(), []int{1}
}

func (x *FileUploadResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *FileUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_FileUpload_proto protoreflect.FileDescriptor

const file_proto_FileUpload_proto_rawDesc = "" +
	"\n" +
	"\x16proto/FileUpload.proto\x12\n" +
	"fileUpload\"-\n" +
	"\x11fileUploadRequest\x12\x18\n" +
	"\aContent\x18\x01 \x01(\fR\aContent\"F\n" +
	"\x12fileUploadResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\bR\x06Status\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage2c\n" +
	"\x12fileUploadServices\x12M\n" +
	"\n" +
	"FileUpload\x12\x1d.fileUpload.fileUploadRequest\x1a\x1e.fileUpload.fileUploadResponse\"\x00B\x0fZ\rmessage/protob\x06proto3"

var (
	file_proto_FileUpload_proto_rawDescOnce sync.Once
	file_proto_FileUpload_proto_rawDescData []byte
)

func file_proto_FileUpload_proto_rawDescGZIP() []byte {
	file_proto_FileUpload_proto_rawDescOnce.Do(func() {
		file_proto_FileUpload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_FileUpload_proto_rawDesc), len(file_proto_FileUpload_proto_rawDesc)))
	})
	return file_proto_FileUpload_proto_rawDescData
}

var file_proto_FileUpload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_FileUpload_proto_goTypes = []any{
	(*FileUploadRequest)(nil),  // 0: fileUpload.fileUploadRequest
	(*FileUploadResponse)(nil), // 1: fileUpload.fileUploadResponse
}
var file_proto_FileUpload_proto_depIdxs = []int32{
	0, // 0: fileUpload.fileUploadServices.FileUpload:input_type -> fileUpload.fileUploadRequest
	1, // 1: fileUpload.fileUploadServices.FileUpload:output_type -> fileUpload.fileUploadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_FileUpload_proto_init() }
func file_proto_FileUpload_proto_init() {
	if File_proto_FileUpload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_FileUpload_proto_rawDesc), len(file_proto_FileUpload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_FileUpload_proto_goTypes,
		DependencyIndexes: file_proto_FileUpload_proto_depIdxs,
		MessageInfos:      file_proto_FileUpload_proto_msgTypes,
	}.Build()
	File_proto_FileUpload_proto = out.File
	file_proto_FileUpload_proto_goTypes = nil
	file_proto_FileUpload_proto_depIdxs = nil
}
