// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/FileUpload.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileUploadServices_FileUpload_FullMethodName = "/fileUpload.fileUploadServices/FileUpload"
)

// FileUploadServicesClient is the client API for FileUploadServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileUploadServicesClient interface {
	FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error)
}

type fileUploadServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewFileUploadServicesClient(cc grpc.ClientConnInterface) FileUploadServicesClient {
	return &fileUploadServicesClient{cc}
}

func (c *fileUploadServicesClient) FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileUploadResponse)
	err := c.cc.Invoke(ctx, FileUploadServices_FileUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileUploadServicesServer is the server API for FileUploadServices service.
// All implementations must embed UnimplementedFileUploadServicesServer
// for forward compatibility.
type FileUploadServicesServer interface {
	FileUpload(context.Context, *FileUploadRequest) (*FileUploadResponse, error)
	mustEmbedUnimplementedFileUploadServicesServer()
}

// UnimplementedFileUploadServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileUploadServicesServer struct{}

func (UnimplementedFileUploadServicesServer) FileUpload(context.Context, *FileUploadRequest) (*FileUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileUpload not implemented")
}
func (UnimplementedFileUploadServicesServer) mustEmbedUnimplementedFileUploadServicesServer() {}
func (UnimplementedFileUploadServicesServer) testEmbeddedByValue()                            {}

// UnsafeFileUploadServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileUploadServicesServer will
// result in compilation errors.
type UnsafeFileUploadServicesServer interface {
	mustEmbedUnimplementedFileUploadServicesServer()
}

func RegisterFileUploadServicesServer(s grpc.ServiceRegistrar, srv FileUploadServicesServer) {
	// If the following call pancis, it indicates UnimplementedFileUploadServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileUploadServices_ServiceDesc, srv)
}

func _FileUploadServices_FileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileUploadServicesServer).FileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileUploadServices_FileUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileUploadServicesServer).FileUpload(ctx, req.(*FileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileUploadServices_ServiceDesc is the grpc.ServiceDesc for FileUploadServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileUploadServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileUpload.fileUploadServices",
	HandlerType: (*FileUploadServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileUpload",
			Handler:    _FileUploadServices_FileUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/FileUpload.proto",
}
