// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/SmsApi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EbulkSms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EbulkSms) Reset() {
	*x = EbulkSms{}
	mi := &file_proto_SmsApi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EbulkSms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EbulkSms) ProtoMessage() {}

func (x *EbulkSms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SmsApi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EbulkSms.ProtoReflect.Descriptor instead.
func (*EbulkSms) Descriptor() ([]byte, []int) {
	return file_proto_SmsApi_proto_rawDescGZIP(), []int{0}
}

type BulkSms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSms) Reset() {
	*x = BulkSms{}
	mi := &file_proto_SmsApi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSms) ProtoMessage() {}

func (x *BulkSms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SmsApi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSms.ProtoReflect.Descriptor instead.
func (*BulkSms) Descriptor() ([]byte, []int) {
	return file_proto_SmsApi_proto_rawDescGZIP(), []int{1}
}

type EbulkSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EbulkSmsResponse) Reset() {
	*x = EbulkSmsResponse{}
	mi := &file_proto_SmsApi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EbulkSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EbulkSmsResponse) ProtoMessage() {}

func (x *EbulkSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SmsApi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EbulkSmsResponse.ProtoReflect.Descriptor instead.
func (*EbulkSmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_SmsApi_proto_rawDescGZIP(), []int{2}
}

func (x *EbulkSmsResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type BulkSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSmsResponse) Reset() {
	*x = BulkSmsResponse{}
	mi := &file_proto_SmsApi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSmsResponse) ProtoMessage() {}

func (x *BulkSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SmsApi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSmsResponse.ProtoReflect.Descriptor instead.
func (*BulkSmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_SmsApi_proto_rawDescGZIP(), []int{3}
}

func (x *BulkSmsResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_SmsApi_proto protoreflect.FileDescriptor

const file_proto_SmsApi_proto_rawDesc = "" +
	"\n" +
	"\x12proto/SmsApi.proto\x12\x05admin\"\n" +
	"\n" +
	"\bEbulkSms\"\t\n" +
	"\aBulkSms\".\n" +
	"\x10EbulkSmsResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"-\n" +
	"\x0fBulkSmsResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\x8a\x01\n" +
	"\vSmsServices\x12>\n" +
	"\x0eEbulkSmsWallet\x12\x0f.admin.EbulkSms\x1a\x17.admin.EbulkSmsResponse\"\x000\x01\x12;\n" +
	"\rBulkSmsWallet\x12\x0e.admin.BulkSms\x1a\x16.admin.BulkSmsResponse\"\x000\x01B\x0fZ\rmessage/protob\x06proto3"

var (
	file_proto_SmsApi_proto_rawDescOnce sync.Once
	file_proto_SmsApi_proto_rawDescData []byte
)

func file_proto_SmsApi_proto_rawDescGZIP() []byte {
	file_proto_SmsApi_proto_rawDescOnce.Do(func() {
		file_proto_SmsApi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_SmsApi_proto_rawDesc), len(file_proto_SmsApi_proto_rawDesc)))
	})
	return file_proto_SmsApi_proto_rawDescData
}

var file_proto_SmsApi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_SmsApi_proto_goTypes = []any{
	(*EbulkSms)(nil),         // 0: admin.EbulkSms
	(*BulkSms)(nil),          // 1: admin.BulkSms
	(*EbulkSmsResponse)(nil), // 2: admin.EbulkSmsResponse
	(*BulkSmsResponse)(nil),  // 3: admin.BulkSmsResponse
}
var file_proto_SmsApi_proto_depIdxs = []int32{
	0, // 0: admin.SmsServices.EbulkSmsWallet:input_type -> admin.EbulkSms
	1, // 1: admin.SmsServices.BulkSmsWallet:input_type -> admin.BulkSms
	2, // 2: admin.SmsServices.EbulkSmsWallet:output_type -> admin.EbulkSmsResponse
	3, // 3: admin.SmsServices.BulkSmsWallet:output_type -> admin.BulkSmsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_SmsApi_proto_init() }
func file_proto_SmsApi_proto_init() {
	if File_proto_SmsApi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_SmsApi_proto_rawDesc), len(file_proto_SmsApi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_SmsApi_proto_goTypes,
		DependencyIndexes: file_proto_SmsApi_proto_depIdxs,
		MessageInfos:      file_proto_SmsApi_proto_msgTypes,
	}.Build()
	File_proto_SmsApi_proto = out.File
	file_proto_SmsApi_proto_goTypes = nil
	file_proto_SmsApi_proto_depIdxs = nil
}
