// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/SmsApi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EbulkSms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EbulkSms) Reset() {
	*x = EbulkSms{}
	mi := &file_proto_SmsApi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EbulkSms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EbulkSms) ProtoMessage() {}

func (x *EbulkSms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SmsApi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EbulkSms.ProtoReflect.Descriptor instead.
func (*EbulkSms) Descriptor() ([]byte, []int) {
	return file_proto_SmsApi_proto_rawDescGZIP(), []int{0}
}

type BulkSms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSms) Reset() {
	*x = BulkSms{}
	mi := &file_proto_SmsApi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSms) ProtoMessage() {}

func (x *BulkSms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SmsApi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSms.ProtoReflect.Descriptor instead.
func (*BulkSms) Descriptor() ([]byte, []int) {
	return file_proto_SmsApi_proto_rawDescGZIP(), []int{1}
}

var File_proto_SmsApi_proto protoreflect.FileDescriptor

const file_proto_SmsApi_proto_rawDesc = "" +
	"\n" +
	"\x12proto/SmsApi.proto\x12\x05admin\"\n" +
	"\n" +
	"\bEbulkSms\"\t\n" +
	"\aBulkSms2z\n" +
	"\vSmsServices\x126\n" +
	"\x0eEbulkSmsWallet\x12\x0f.admin.EbulkSms\x1a\x0f.admin.EbulkSms\"\x000\x01\x123\n" +
	"\rBulkSmsWallet\x12\x0e.admin.BulkSms\x1a\x0e.admin.BulkSms\"\x000\x01B\x0fZ\rmessage/protob\x06proto3"

var (
	file_proto_SmsApi_proto_rawDescOnce sync.Once
	file_proto_SmsApi_proto_rawDescData []byte
)

func file_proto_SmsApi_proto_rawDescGZIP() []byte {
	file_proto_SmsApi_proto_rawDescOnce.Do(func() {
		file_proto_SmsApi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_SmsApi_proto_rawDesc), len(file_proto_SmsApi_proto_rawDesc)))
	})
	return file_proto_SmsApi_proto_rawDescData
}

var file_proto_SmsApi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_SmsApi_proto_goTypes = []any{
	(*EbulkSms)(nil), // 0: admin.EbulkSms
	(*BulkSms)(nil),  // 1: admin.BulkSms
}
var file_proto_SmsApi_proto_depIdxs = []int32{
	0, // 0: admin.SmsServices.EbulkSmsWallet:input_type -> admin.EbulkSms
	1, // 1: admin.SmsServices.BulkSmsWallet:input_type -> admin.BulkSms
	0, // 2: admin.SmsServices.EbulkSmsWallet:output_type -> admin.EbulkSms
	1, // 3: admin.SmsServices.BulkSmsWallet:output_type -> admin.BulkSms
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_SmsApi_proto_init() }
func file_proto_SmsApi_proto_init() {
	if File_proto_SmsApi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_SmsApi_proto_rawDesc), len(file_proto_SmsApi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_SmsApi_proto_goTypes,
		DependencyIndexes: file_proto_SmsApi_proto_depIdxs,
		MessageInfos:      file_proto_SmsApi_proto_msgTypes,
	}.Build()
	File_proto_SmsApi_proto = out.File
	file_proto_SmsApi_proto_goTypes = nil
	file_proto_SmsApi_proto_depIdxs = nil
}
