// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/Template.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Template struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateName    string                 `protobuf:"bytes,2,opt,name=TemplateName,proto3" json:"TemplateName,omitempty"`
	TemplateContent string                 `protobuf:"bytes,3,opt,name=TemplateContent,proto3" json:"TemplateContent,omitempty"`
	Date            string                 `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_proto_Template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Template) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *Template) GetTemplateContent() string {
	if x != nil {
		return x.TemplateContent
	}
	return ""
}

func (x *Template) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SmsTemplate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SmsTemplateName    string                 `protobuf:"bytes,2,opt,name=SmsTemplateName,proto3" json:"SmsTemplateName,omitempty"`
	SmsTemplateContent string                 `protobuf:"bytes,3,opt,name=SmsTemplateContent,proto3" json:"SmsTemplateContent,omitempty"`
	Date               string                 `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SmsTemplate) Reset() {
	*x = SmsTemplate{}
	mi := &file_proto_Template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsTemplate) ProtoMessage() {}

func (x *SmsTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsTemplate.ProtoReflect.Descriptor instead.
func (*SmsTemplate) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{1}
}

func (x *SmsTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SmsTemplate) GetSmsTemplateName() string {
	if x != nil {
		return x.SmsTemplateName
	}
	return ""
}

func (x *SmsTemplate) GetSmsTemplateContent() string {
	if x != nil {
		return x.SmsTemplateContent
	}
	return ""
}

func (x *SmsTemplate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_Template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TemplateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TemplateName    string                 `protobuf:"bytes,1,opt,name=TemplateName,proto3" json:"TemplateName,omitempty"`
	TemplateContent string                 `protobuf:"bytes,2,opt,name=TemplateContent,proto3" json:"TemplateContent,omitempty"`
	Date            string                 `protobuf:"bytes,3,opt,name=Date,proto3" json:"Date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TemplateRequest) Reset() {
	*x = TemplateRequest{}
	mi := &file_proto_Template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRequest) ProtoMessage() {}

func (x *TemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRequest.ProtoReflect.Descriptor instead.
func (*TemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *TemplateRequest) GetTemplateContent() string {
	if x != nil {
		return x.TemplateContent
	}
	return ""
}

func (x *TemplateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SmsTemplateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SmsTemplateName    string                 `protobuf:"bytes,1,opt,name=SmsTemplateName,proto3" json:"SmsTemplateName,omitempty"`
	SmsTemplateContent string                 `protobuf:"bytes,2,opt,name=SmsTemplateContent,proto3" json:"SmsTemplateContent,omitempty"`
	Date               string                 `protobuf:"bytes,3,opt,name=Date,proto3" json:"Date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SmsTemplateRequest) Reset() {
	*x = SmsTemplateRequest{}
	mi := &file_proto_Template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsTemplateRequest) ProtoMessage() {}

func (x *SmsTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsTemplateRequest.ProtoReflect.Descriptor instead.
func (*SmsTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{4}
}

func (x *SmsTemplateRequest) GetSmsTemplateName() string {
	if x != nil {
		return x.SmsTemplateName
	}
	return ""
}

func (x *SmsTemplateRequest) GetSmsTemplateContent() string {
	if x != nil {
		return x.SmsTemplateContent
	}
	return ""
}

func (x *SmsTemplateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetATemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetATemplateRequest) Reset() {
	*x = GetATemplateRequest{}
	mi := &file_proto_Template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetATemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetATemplateRequest) ProtoMessage() {}

func (x *GetATemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetATemplateRequest.ProtoReflect.Descriptor instead.
func (*GetATemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{5}
}

func (x *GetATemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetATemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetATemplateResponse) Reset() {
	*x = GetATemplateResponse{}
	mi := &file_proto_Template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetATemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetATemplateResponse) ProtoMessage() {}

func (x *GetATemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetATemplateResponse.ProtoReflect.Descriptor instead.
func (*GetATemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{6}
}

func (x *GetATemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type GetAnSmsTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnSmsTemplateRequest) Reset() {
	*x = GetAnSmsTemplateRequest{}
	mi := &file_proto_Template_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnSmsTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnSmsTemplateRequest) ProtoMessage() {}

func (x *GetAnSmsTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnSmsTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetAnSmsTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnSmsTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAnSmsTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmsTemplate   *SmsTemplate           `protobuf:"bytes,1,opt,name=smsTemplate,proto3" json:"smsTemplate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnSmsTemplateResponse) Reset() {
	*x = GetAnSmsTemplateResponse{}
	mi := &file_proto_Template_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnSmsTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnSmsTemplateResponse) ProtoMessage() {}

func (x *GetAnSmsTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnSmsTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetAnSmsTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnSmsTemplateResponse) GetSmsTemplate() *SmsTemplate {
	if x != nil {
		return x.SmsTemplate
	}
	return nil
}

type TemplateEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateEditRequest) Reset() {
	*x = TemplateEditRequest{}
	mi := &file_proto_Template_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateEditRequest) ProtoMessage() {}

func (x *TemplateEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateEditRequest.ProtoReflect.Descriptor instead.
func (*TemplateEditRequest) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{9}
}

func (x *TemplateEditRequest) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type SmsTemplateEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Smstemplate   *SmsTemplate           `protobuf:"bytes,1,opt,name=smstemplate,proto3" json:"smstemplate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsTemplateEditRequest) Reset() {
	*x = SmsTemplateEditRequest{}
	mi := &file_proto_Template_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsTemplateEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsTemplateEditRequest) ProtoMessage() {}

func (x *SmsTemplateEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsTemplateEditRequest.ProtoReflect.Descriptor instead.
func (*SmsTemplateEditRequest) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{10}
}

func (x *SmsTemplateEditRequest) GetSmstemplate() *SmsTemplate {
	if x != nil {
		return x.Smstemplate
	}
	return nil
}

type TemplateFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateFetchRequest) Reset() {
	*x = TemplateFetchRequest{}
	mi := &file_proto_Template_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateFetchRequest) ProtoMessage() {}

func (x *TemplateFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateFetchRequest.ProtoReflect.Descriptor instead.
func (*TemplateFetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{11}
}

type TemplateFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateFetchResponse) Reset() {
	*x = TemplateFetchResponse{}
	mi := &file_proto_Template_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateFetchResponse) ProtoMessage() {}

func (x *TemplateFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Template_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateFetchResponse.ProtoReflect.Descriptor instead.
func (*TemplateFetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_Template_proto_rawDescGZIP(), []int{12}
}

var File_proto_Template_proto protoreflect.FileDescriptor

const file_proto_Template_proto_rawDesc = "" +
	"\n" +
	"\x14proto/Template.proto\x12\tTemplates\"|\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fTemplateName\x18\x02 \x01(\tR\fTemplateName\x12(\n" +
	"\x0fTemplateContent\x18\x03 \x01(\tR\x0fTemplateContent\x12\x12\n" +
	"\x04Date\x18\x04 \x01(\tR\x04Date\"\x8b\x01\n" +
	"\vSmsTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x0fSmsTemplateName\x18\x02 \x01(\tR\x0fSmsTemplateName\x12.\n" +
	"\x12SmsTemplateContent\x18\x03 \x01(\tR\x12SmsTemplateContent\x12\x12\n" +
	"\x04Date\x18\x04 \x01(\tR\x04Date\"<\n" +
	"\bResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\bR\x06Status\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"s\n" +
	"\x0fTemplateRequest\x12\"\n" +
	"\fTemplateName\x18\x01 \x01(\tR\fTemplateName\x12(\n" +
	"\x0fTemplateContent\x18\x02 \x01(\tR\x0fTemplateContent\x12\x12\n" +
	"\x04Date\x18\x03 \x01(\tR\x04Date\"\x82\x01\n" +
	"\x12SmsTemplateRequest\x12(\n" +
	"\x0fSmsTemplateName\x18\x01 \x01(\tR\x0fSmsTemplateName\x12.\n" +
	"\x12SmsTemplateContent\x18\x02 \x01(\tR\x12SmsTemplateContent\x12\x12\n" +
	"\x04Date\x18\x03 \x01(\tR\x04Date\"%\n" +
	"\x13GetATemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x14GetATemplateResponse\x12/\n" +
	"\btemplate\x18\x01 \x01(\v2\x13.Templates.TemplateR\btemplate\")\n" +
	"\x17GetAnSmsTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x18GetAnSmsTemplateResponse\x128\n" +
	"\vsmsTemplate\x18\x01 \x01(\v2\x16.Templates.SmsTemplateR\vsmsTemplate\"F\n" +
	"\x13TemplateEditRequest\x12/\n" +
	"\btemplate\x18\x01 \x01(\v2\x13.Templates.TemplateR\btemplate\"R\n" +
	"\x16SmsTemplateEditRequest\x128\n" +
	"\vsmstemplate\x18\x01 \x01(\v2\x16.Templates.SmsTemplateR\vsmstemplate\"\x16\n" +
	"\x14TemplateFetchRequest\"\x17\n" +
	"\x15TemplateFetchResponse2\xd3\x04\n" +
	"\x10TemplateServices\x12H\n" +
	"\x13CreateEmailTemplate\x12\x1a.Templates.TemplateRequest\x1a\x13.Templates.Response\"\x00\x12I\n" +
	"\x11CreateSmsTemplate\x12\x1d.Templates.SmsTemplateRequest\x1a\x13.Templates.Response\"\x00\x12U\n" +
	"\fAllTemplates\x12\x1f.Templates.TemplateFetchRequest\x1a .Templates.TemplateFetchResponse\"\x000\x01\x12J\n" +
	"\x11EditEmailTemplate\x12\x1e.Templates.TemplateEditRequest\x1a\x13.Templates.Response\"\x00\x12K\n" +
	"\x0fEditSmsTemplate\x12!.Templates.SmsTemplateEditRequest\x1a\x13.Templates.Response\"\x00\x12Y\n" +
	"\x14GetEmailTemplateById\x12\x1e.Templates.GetATemplateRequest\x1a\x1f.Templates.GetATemplateResponse\"\x00\x12_\n" +
	"\x12GetSmsTemplateById\x12\".Templates.GetAnSmsTemplateRequest\x1a#.Templates.GetAnSmsTemplateResponse\"\x00B\x0fZ\rmessage/protob\x06proto3"

var (
	file_proto_Template_proto_rawDescOnce sync.Once
	file_proto_Template_proto_rawDescData []byte
)

func file_proto_Template_proto_rawDescGZIP() []byte {
	file_proto_Template_proto_rawDescOnce.Do(func() {
		file_proto_Template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Template_proto_rawDesc), len(file_proto_Template_proto_rawDesc)))
	})
	return file_proto_Template_proto_rawDescData
}

var file_proto_Template_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_Template_proto_goTypes = []any{
	(*Template)(nil),                 // 0: Templates.Template
	(*SmsTemplate)(nil),              // 1: Templates.SmsTemplate
	(*Response)(nil),                 // 2: Templates.Response
	(*TemplateRequest)(nil),          // 3: Templates.TemplateRequest
	(*SmsTemplateRequest)(nil),       // 4: Templates.SmsTemplateRequest
	(*GetATemplateRequest)(nil),      // 5: Templates.GetATemplateRequest
	(*GetATemplateResponse)(nil),     // 6: Templates.GetATemplateResponse
	(*GetAnSmsTemplateRequest)(nil),  // 7: Templates.GetAnSmsTemplateRequest
	(*GetAnSmsTemplateResponse)(nil), // 8: Templates.GetAnSmsTemplateResponse
	(*TemplateEditRequest)(nil),      // 9: Templates.TemplateEditRequest
	(*SmsTemplateEditRequest)(nil),   // 10: Templates.SmsTemplateEditRequest
	(*TemplateFetchRequest)(nil),     // 11: Templates.TemplateFetchRequest
	(*TemplateFetchResponse)(nil),    // 12: Templates.TemplateFetchResponse
}
var file_proto_Template_proto_depIdxs = []int32{
	0,  // 0: Templates.GetATemplateResponse.template:type_name -> Templates.Template
	1,  // 1: Templates.GetAnSmsTemplateResponse.smsTemplate:type_name -> Templates.SmsTemplate
	0,  // 2: Templates.TemplateEditRequest.template:type_name -> Templates.Template
	1,  // 3: Templates.SmsTemplateEditRequest.smstemplate:type_name -> Templates.SmsTemplate
	3,  // 4: Templates.TemplateServices.CreateEmailTemplate:input_type -> Templates.TemplateRequest
	4,  // 5: Templates.TemplateServices.CreateSmsTemplate:input_type -> Templates.SmsTemplateRequest
	11, // 6: Templates.TemplateServices.AllTemplates:input_type -> Templates.TemplateFetchRequest
	9,  // 7: Templates.TemplateServices.EditEmailTemplate:input_type -> Templates.TemplateEditRequest
	10, // 8: Templates.TemplateServices.EditSmsTemplate:input_type -> Templates.SmsTemplateEditRequest
	5,  // 9: Templates.TemplateServices.GetEmailTemplateById:input_type -> Templates.GetATemplateRequest
	7,  // 10: Templates.TemplateServices.GetSmsTemplateById:input_type -> Templates.GetAnSmsTemplateRequest
	2,  // 11: Templates.TemplateServices.CreateEmailTemplate:output_type -> Templates.Response
	2,  // 12: Templates.TemplateServices.CreateSmsTemplate:output_type -> Templates.Response
	12, // 13: Templates.TemplateServices.AllTemplates:output_type -> Templates.TemplateFetchResponse
	2,  // 14: Templates.TemplateServices.EditEmailTemplate:output_type -> Templates.Response
	2,  // 15: Templates.TemplateServices.EditSmsTemplate:output_type -> Templates.Response
	6,  // 16: Templates.TemplateServices.GetEmailTemplateById:output_type -> Templates.GetATemplateResponse
	8,  // 17: Templates.TemplateServices.GetSmsTemplateById:output_type -> Templates.GetAnSmsTemplateResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_Template_proto_init() }
func file_proto_Template_proto_init() {
	if File_proto_Template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Template_proto_rawDesc), len(file_proto_Template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Template_proto_goTypes,
		DependencyIndexes: file_proto_Template_proto_depIdxs,
		MessageInfos:      file_proto_Template_proto_msgTypes,
	}.Build()
	File_proto_Template_proto = out.File
	file_proto_Template_proto_goTypes = nil
	file_proto_Template_proto_depIdxs = nil
}
