name: Neo Sms - Email Notification

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push-to-dockerhub:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Client Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:${{ vars.CLIENT_TAG }} ./nginx
          docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:${{ vars.CLIENT_TAG }}
      
      - name: Build and push Server Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:${{ vars.SERVER_TAG }} ./server
          docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:${{ vars.SERVER_TAG }}

      - name: Build and push Envoy Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:${{ vars.ENVOY_TAG }} .
          docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:${{ vars.ENVOY_TAG }}
